# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - video-frontend-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # required for actions/checkout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # No build needed â€“ just PHP + static files
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .   # all files in the repo

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # required for requesting the JWT
      contents: read    # required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0DC39774DE88408AB23DD023EBEF54AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6211EC46FB774327B17D2938C874668B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F3BAFE94D654C02BA996A3FE50642B9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'video-frontend-azure'
          slot-name: 'Production'
          package: .
